import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>My Posts</h1>
        <ul className={styles.posts}>
          <li>
            <p>This is a tweet post</p>
            <p className={styles.date}>{Date()}</p>
          </li>
          <li>
            <p>This is a tweet post</p>
            <p className={styles.date}>{Date()}</p>
          </li>
          <li>
            <p>This is a tweet post</p>
            <p className={styles.date}>{Date()}</p>
          </li>
        </ul>
      </main>
    </div>
  );
}
